void cleanTheRoom(){
    //cleanright();
    repeat(5){
        while(frontIsClear()){
            if(onBeeper()){
                pickBeeper();
            }
            moveForward();
        }
        turnLeft();
        if(onBeeper()){
            pickBeeper();
        }
        if(frontIsClear()){
            moveForward();
            turnLeft();
        }
        while(frontIsClear()){
            if(onBeeper()){
                pickBeeper();
            }
            moveForward();
        }
        if(onBeeper()){
            pickBeeper();
        }
        turnRight();
        if(frontIsClear()){
            moveForward();
            turnRight();
        }
    }
}